name: crypto_viewer
description: Application for viewing the current price of crypto
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.19.0
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true

#  assets:
#    - assets/
